"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Trans = exports.transformGatsbyNodeData = exports.SUBS_REG_EX = exports.resources = exports.lang = exports.defaultNS = exports.t = exports.use = void 0;
var i18n_1 = require("./i18n");
Object.defineProperty(exports, "use", { enumerable: true, get: function () { return i18n_1.use; } });
Object.defineProperty(exports, "t", { enumerable: true, get: function () { return i18n_1.t; } });
Object.defineProperty(exports, "defaultNS", { enumerable: true, get: function () { return i18n_1.defaultNS; } });
Object.defineProperty(exports, "lang", { enumerable: true, get: function () { return i18n_1.lang; } });
Object.defineProperty(exports, "resources", { enumerable: true, get: function () { return i18n_1.resources; } });
Object.defineProperty(exports, "SUBS_REG_EX", { enumerable: true, get: function () { return i18n_1.SUBS_REG_EX; } });
var transformGatsbyNodeData_1 = require("./utils/transformGatsbyNodeData");
Object.defineProperty(exports, "transformGatsbyNodeData", { enumerable: true, get: function () { return transformGatsbyNodeData_1.transformGatsbyNodeData; } });
var Trans_1 = require("./Trans");
Object.defineProperty(exports, "Trans", { enumerable: true, get: function () { return Trans_1.Trans; } });
